name = "shroud-website"
type = "javascript"
route = ''
account_id = '343497d40c13ff71b5e8a65ad9b2e5ac'
usage_model = ''
compatibility_flags = []
workers_dev = true
compatibility_date = "2021-11-06"

[site]
bucket = ".output/public"
entry-point = ".output"

[env.production]
zone_id = '4a1a4d76704fd392a347d08ea9892750'
route = 'shroud.email/*'

[build]
command = "NITRO_PRESET=cloudflare npm run build"
upload.format = "service-worker"
